"""Admin Routes.

The eight reference-data entities (clients, contacts, producers, installers,
services, materials, tools, equipment) are all plain CRUD over a repository, so
they are declared as :class:`CrudSpec` values and their views are generated by
:func:`register_crud`.

Users stay hand-written: password hashing, username uniqueness and the
self-deletion guard make them different enough that squeezing them into the
generic path would obscure both.
"""

import logging

from flask import flash, redirect, render_template, request, session, url_for

from app.blueprints.admin import admin_bp
from app.blueprints.admin.crud import CrudSpec, register_crud
from app.blueprints.auth.routes import admin_required
from app.blueprints.plans.routes import annotate_plan_statuses
from app.querying import merge_filters, paginate_query, read_page, text_filter
from app.repositories import (
    clients_repo,
    contacts_repo,
    equipment_repo,
    installers_repo,
    materials_repo,
    plans_repo,
    producers_repo,
    services_repo,
    tools_repo,
    users_repo,
)
from app.security import hash_password

logger = logging.getLogger(__name__)

MIN_PASSWORD_LENGTH = 8


@admin_bp.route('/')
@admin_required
def dashboard():
    return render_template('admin/dashboard.html')


# ============================================================================
# USERS — hand-written: credentials need handling the generic CRUD should not
# know about.
# ============================================================================

@admin_bp.route('/users')
@admin_required
def list_users():
    q = request.args.get('q', '').strip()
    filters = merge_filters(text_filter(q, ('nome', 'username')))
    page, per_page = read_page()
    pg = paginate_query(users_repo, filters, [('nome', 1)], page, per_page)
    return render_template(
        'admin/users/list.html',
        users=pg['items'],
        list_endpoint='admin.list_users',
        q=q,
        **pg,
    )


@admin_bp.route('/users/new', methods=['GET', 'POST'])
@admin_required
def new_user():
    if request.method == 'POST':
        data = {
            'nome': request.form.get('nome', '').strip(),
            'username': request.form.get('username', '').strip(),
            'password': request.form.get('password', '').strip(),
            'role': request.form.get('role', 'user'),
            'active': request.form.get('active') == 'true',
        }

        if not data['nome']:
            flash('Nome é obrigatório.', 'error')
        elif data['username'] and len(data['password']) < MIN_PASSWORD_LENGTH:
            flash(f'A senha deve ter pelo menos {MIN_PASSWORD_LENGTH} caracteres.', 'error')
        elif data['username'] and users_repo.find_one_by('username', data['username']):
            flash('Nome de usuário já existe.', 'error')
        else:
            # Never persist the plaintext password.
            data['password'] = hash_password(data['password']) if data['password'] else ''
            users_repo.create(data)
            logger.info('Admin %s created user %r', session.get('username'), data['username'])
            flash('Usuário criado com sucesso!', 'success')
            return redirect(url_for('admin.list_users'))

    return render_template('admin/users/form.html', user=None)


@admin_bp.route('/users/<id>/edit', methods=['GET', 'POST'])
@admin_required
def edit_user(id):
    user = users_repo.get_by_id(id)
    if not user:
        flash('Usuário não encontrado.', 'error')
        return redirect(url_for('admin.list_users'))

    if request.method == 'POST':
        data = {
            'nome': request.form.get('nome', '').strip(),
            'username': request.form.get('username', '').strip(),
            'role': request.form.get('role', 'user'),
            'active': request.form.get('active') == 'true',
        }
        password = request.form.get('password', '').strip()
        username_taken = (
            data['username']
            and data['username'] != user.get('username')
            and users_repo.find_one_by('username', data['username'])
        )

        if not data['nome']:
            flash('Nome é obrigatório.', 'error')
        elif password and len(password) < MIN_PASSWORD_LENGTH:
            flash(f'A senha deve ter pelo menos {MIN_PASSWORD_LENGTH} caracteres.', 'error')
        elif username_taken:
            flash('Nome de usuário já existe.', 'error')
        else:
            # An empty password field means "leave the current one alone".
            if password:
                data['password'] = hash_password(password)
            users_repo.update(id, data)
            logger.info('Admin %s updated user %s', session.get('username'), id)
            flash('Usuário atualizado!', 'success')
            return redirect(url_for('admin.list_users'))

    return render_template('admin/users/form.html', user=user)


@admin_bp.route('/users/<id>/delete', methods=['POST'])
@admin_required
def delete_user(id):
    user = users_repo.get_by_id(id)
    if user and user.get('username') == 'admin':
        flash('Não é possível excluir o administrador principal.', 'error')
    elif id == session.get('user_id'):
        # Locking yourself out mid-session is never the intent.
        flash('Você não pode excluir a própria conta.', 'error')
    else:
        users_repo.delete(id)
        logger.info('Admin %s deleted user %s', session.get('username'), id)
        flash('Usuário removido.', 'success')
    return redirect(url_for('admin.list_users'))


# ============================================================================
# EQUIPMENT hooks — equipment is CRUD plus "which active plans use this?"
# ============================================================================

def _active_plans_using_equipment():
    """Plans that reference equipment and are not concluded.

    Returns a mapping of lowercased equipment name -> list of plan names.
    """
    plans = plans_repo.find({'equipamentos': {'$exists': True, '$ne': []}})
    usage: dict[str, list[dict]] = {}
    for plan in annotate_plan_statuses(plans):
        if plan['_status'] == 'Concluído':
            continue
        for name in plan.get('equipamentos', []):
            usage.setdefault(str(name).lower(), []).append({
                'id': plan.get('project_id', ''),
                'nome': plan.get('nome_projeto', 'Sem Nome'),
            })
    return usage


def annotate_equipment_usage(items):
    """Mark each equipment row as in use or free, for the list view."""
    usage = _active_plans_using_equipment()
    for eq in items:
        projetos = usage.get(eq.get('nome', '').lower(), [])
        eq['status'] = 'Em Uso' if projetos else 'Livre'
        eq['projetos_relacionados'] = [p['nome'] for p in projetos]


def equipment_form_context(item):
    """Related active projects, shown on the equipment edit form."""
    usage = _active_plans_using_equipment()
    return {'projetos_relacionados': usage.get(item.get('nome', '').lower(), [])}


# ============================================================================
# Generated CRUD
# ============================================================================

CRUD_SPECS = [
    CrudSpec(
        name='clients', singular='client', repo=clients_repo,
        fields=('nome', 'email', 'telefone', 'documento'),
        search_fields=('nome', 'email', 'telefone'),
        label='Cliente',
        created='Cliente criado com sucesso!',
        updated='Cliente atualizado!',
        deleted='Cliente removido.',
        missing='Cliente não encontrado.',
    ),
    CrudSpec(
        name='contacts', singular='contact', repo=contacts_repo,
        fields=('nome', 'telefone', 'email'),
        search_fields=('nome', 'email', 'telefone'),
        label='Contato',
        created='Contato criado com sucesso!',
        updated='Contato atualizado!',
        deleted='Contato removido.',
        missing='Contato não encontrado.',
    ),
    CrudSpec(
        name='producers', singular='producer', repo=producers_repo,
        fields=('nome', 'telefone', 'email'),
        search_fields=('nome', 'email', 'telefone'),
        label='Produtor',
        created='Produtor criado com sucesso!',
        updated='Produtor atualizado!',
        deleted='Produtor removido.',
        missing='Produtor não encontrado.',
    ),
    CrudSpec(
        name='installers', singular='installer', repo=installers_repo,
        fields=('nome', 'telefone', 'email', 'especialidade'),
        search_fields=('nome', 'email', 'especialidade'),
        label='Instalador',
        created='Instalador criado com sucesso!',
        updated='Instalador atualizado!',
        deleted='Instalador removido.',
        missing='Instalador não encontrado.',
    ),
    CrudSpec(
        name='services', singular='service', repo=services_repo,
        fields=('tipo_servico', 'responsavel'),
        search_fields=('tipo_servico', 'responsavel'),
        label='Serviço',
        created='Serviço criado com sucesso!',
        updated='Serviço atualizado!',
        deleted='Serviço removido.',
        missing='Serviço não encontrado.',
        required='tipo_servico',
        required_message='Tipo de serviço é obrigatório.',
        sort_field='tipo_servico',
    ),
    CrudSpec(
        name='materials', singular='material', repo=materials_repo,
        fields=('nome',), search_fields=('nome',),
        label='Material',
        created='Material criado com sucesso!',
        updated='Material atualizado!',
        deleted='Material removido.',
        missing='Material não encontrado.',
        has_image=True,
    ),
    CrudSpec(
        name='tools', singular='tool', repo=tools_repo,
        fields=('nome',), search_fields=('nome',),
        label='Ferramenta',
        created='Ferramenta criada com sucesso!',
        updated='Ferramenta atualizada!',
        deleted='Ferramenta removida.',
        missing='Ferramenta não encontrada.',
        has_image=True,
    ),
    CrudSpec(
        name='equipment', singular='equipment', repo=equipment_repo,
        fields=('nome',), search_fields=('nome',),
        label='Equipamento',
        created='Equipamento criado com sucesso!',
        updated='Equipamento atualizado!',
        deleted='Equipamento removido.',
        missing='Equipamento não encontrado.',
        has_image=True,
        annotate_page=annotate_equipment_usage,
        form_context=equipment_form_context,
    ),
]

for _spec in CRUD_SPECS:
    register_crud(admin_bp, _spec)
